In [ ]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option('display.max_columns', None)

# Display wider tables
pd.set_option('display.width', None)

In [ ]:
influencers = pd.read_excel("influencers.xlsx")

campaigns = pd.read_excel("campaigns.xlsx")

campaign_perf = pd.read_excel("influencer campaign performance.xlsx")

orders = pd.read_excel("orders.xlsx")

products = pd.read_excel("products.xlsx")

customers = pd.read_excel("customer demographics.xlsx")

In [ ]:
datasets = {
    "Influencers": influencers,
    "Campaigns": campaigns,
    "Campaign Performance": campaign_perf,
    "Orders": orders,
    "Products": products,
    "Customers": customers
}

In [ ]:
for name, df in datasets.items():
    print("="*70)
    print(f"{name}")
    print("="*70)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    display(df.head())

    print("\n")

======================================================================
Influencers
======================================================================

Shape:
(20, 9)

Columns:
['Influencer_ID', 'Name', 'Gender', 'Platform', 'Follower_Count', 'Tier', 'Location', 'Avg_Cost_Per_Post', 'Audience_Location_Match_pct']

First 5 rows:

,Influencer_ID,Name,Gender,Platform,Follower_Count,Tier,Location,Avg_Cost_Per_Post,Audience_Location_Match_pct
0,INF001,StyleSensei,Female,TikTok,80832,Micro,Punjab,1000,61.8
1,INF002,VibeGuru,Male,Instagram,326621,Macro,Odisha,8000,54.2
2,INF003,GenZFashion,Female,Instagram,11799,Nano,Karnataka,300,60.5
3,INF004,TheStreetLook,Male,YouTube,749531,Macro,Odisha,8000,59.5
4,INF005,DailyDrapes,Female,TikTok,311330,Macro,Bihar,8000,60.6

======================================================================
Campaigns
======================================================================

Shape:
(10, 10)

Columns:
['Campaign_ID', 'Product_Category', 'Budget', 'Goal_Type', 'Target_Gender', 'Product_Focus_Type', 'Start_Date', 'End_Date', 'Conversion_Rate_Target_pct', 'Platform']

First 5 rows:

,Campaign_ID,Product_Category,Budget,Goal_Type,Target_Gender,Product_Focus_Type,Start_Date,End_Date,Conversion_Rate_Target_pct,Platform
0,CMP001,Jackets,410757,Conversions,Male,Category,2025-03-24,2025-05-23,2.42,Instagram
1,CMP002,Pants,725044,Conversions,Female,Single Product,2024-05-15,2024-06-07,2.11,TikTok
2,CMP003,Accessories,635558,Conversions,Unisex,Collection,2024-07-04,2024-08-02,5.49,YouTube
3,CMP004,Dresses,209091,Conversions,Male,Single Product,2024-11-17,2024-12-12,4.56,Instagram
4,CMP005,Pants,1007813,Awareness,Female,Category,2024-05-08,2024-06-27,4.87,TikTok

======================================================================
Campaign Performance
======================================================================

Shape:
(60, 8)

Columns:
['Source_Influencer_ID', 'Campaign_ID', 'Conversions', 'Revenue_Generated', 'Cost', 'ROI', 'Product_Focus_Type', 'Main_Product_ID']

First 5 rows:

,Source_Influencer_ID,Campaign_ID,Conversions,Revenue_Generated,Cost,ROI,Product_Focus_Type,Main_Product_ID
0,INF001,CMP002,778,2263654.98,3000,753.5517,Single Product,PRD021
1,INF001,CMP005,421,1323393.18,3000,440.1311,Category,NaN
2,INF001,CMP010,558,1846970.34,3000,614.6568,Single Product,PRD012
3,INF002,CMP006,1079,4630686.20,24000,191.9453,Category,NaN
4,INF002,CMP007,1145,4851254.62,24000,201.1356,Collection,NaN

======================================================================
Orders
======================================================================

Shape:
(100000, 12)

Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Unit_Price', 'Discount_Code_Used', 'Discount_Amount', 'Source_Influencer_ID', 'Campaign_ID', 'Total_Amount', 'Channel']

First 5 rows:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Unit_Price,Discount_Code_Used,Discount_Amount,Source_Influencer_ID,Campaign_ID,Total_Amount,Channel
0,ORD100001,2024-09-12,CUST100000,PRD024,1,1760,INF008CODE,96.91,INF008,CMP009,1663.09,Instagram
1,ORD100002,2024-10-15,CUST100001,PRD007,1,6036,INF003CODE,162.05,INF003,CMP002,5873.95,Instagram
2,ORD100003,2024-03-22,CUST100002,PRD007,1,6036,INF019CODE,347.31,INF019,CMP005,5688.69,Instagram
3,ORD100004,2025-01-10,CUST100003,PRD008,1,6046,INF019CODE,352.84,INF019,CMP004,5693.16,Instagram
4,ORD100005,2025-03-27,CUST100004,PRD024,1,1760,INF012CODE,132.66,INF012,CMP007,1627.34,YouTube

======================================================================
Products
======================================================================

Shape:
(25, 7)

Columns:
['Product_ID', 'Category', 'Sub_Category', 'Price', 'Gender_Target', 'Season', 'Launch_Date']

First 5 rows:

,Product_ID,Category,Sub_Category,Price,Gender_Target,Season,Launch_Date
0,PRD001,Accessories,Cotton,1076,Unisex,All-Season,2025-01-01
1,PRD002,Accessories,Cotton,2194,Female,All-Season,2023-04-23
2,PRD003,Dresses,Denim,3468,Male,All-Season,2022-09-02
3,PRD004,Jackets,Cotton,690,Male,Winter,2024-03-11
4,PRD005,Pants,Cotton,1395,Female,All-Season,2023-09-12

======================================================================
Customers
======================================================================

Shape:
(90000, 11)

Columns:
['Customer_ID', 'Gender', 'Age', 'Location', 'Income_Bracket', 'Preferred_Style', 'Source_Influencer_ID', 'Source_Campaign_ID', 'Is_New_Customer', 'Lifetime_Value', 'Avg_Order_Value']

First 5 rows:

,Customer_ID,Gender,Age,Location,Income_Bracket,Preferred_Style,Source_Influencer_ID,Source_Campaign_ID,Is_New_Customer,Lifetime_Value,Avg_Order_Value
0,CUST100000,Male,40,Haryana,Low,Casual,INF008,CMP009,True,1663.09,1663.09
1,CUST100001,Female,28,Rajasthan,Low,Boho,INF003,CMP002,True,5873.95,5873.95
2,CUST100002,Female,30,Andhra Pradesh,Medium,Streetwear,INF019,CMP005,False,9042.79,4521.39
3,CUST100003,Other,20,Odisha,Low,Boho,INF019,CMP004,True,5693.16,5693.16
4,CUST100004,Male,26,Punjab,Low,Athleisure,INF012,CMP007,False,7467.49,3733.74

In [ ]:
for name, df in datasets.items():
    print("="*70)
    print(name)
    print("="*70)

    display(df.dtypes.to_frame("Data Type"))

    print()

======================================================================
Influencers
======================================================================

                            Data Type
Influencer_ID                  object
Name                           object
Gender                         object
Platform                       object
Follower_Count                  int64
Tier                           object
Location                       object
Avg_Cost_Per_Post               int64
Audience_Location_Match_pct   float64

======================================================================
Campaigns
======================================================================

                                 Data Type
Campaign_ID                         object
Product_Category                    object
Budget                               int64
Goal_Type                           object
Target_Gender                       object
Product_Focus_Type                  object
Start_Date                  datetime64[ns]
End_Date                    datetime64[ns]
Conversion_Rate_Target_pct         float64
Platform                            object

======================================================================
Campaign Performance
======================================================================

                     Data Type
Source_Influencer_ID    object
Campaign_ID             object
Conversions              int64
Revenue_Generated      float64
Cost                     int64
ROI                    float64
Product_Focus_Type      object
Main_Product_ID         object

======================================================================
Orders
======================================================================

                           Data Type
Order_ID                      object
Order_Date            datetime64[ns]
Customer_ID                   object
Product_ID                    object
Quantity                       int64
Unit_Price                     int64
Discount_Code_Used            object
Discount_Amount              float64
Source_Influencer_ID          object
Campaign_ID                   object
Total_Amount                 float64
Channel                       object

======================================================================
Products
======================================================================

                    Data Type
Product_ID             object
Category               object
Sub_Category           object
Price                   int64
Gender_Target          object
Season                 object
Launch_Date    datetime64[ns]

======================================================================
Customers
======================================================================

                     Data Type
Customer_ID             object
Gender                  object
Age                      int64
Location                object
Income_Bracket          object
Preferred_Style         object
Source_Influencer_ID    object
Source_Campaign_ID      object
Is_New_Customer           bool
Lifetime_Value         float64
Avg_Order_Value        float64

In [ ]:
# ============================================
# Missing Values Summary
# ============================================

for name, df in datasets.items():

    print("="*70)
    print(name)
    print("="*70)

    missing = df.isnull().sum()

    missing = missing[missing > 0]

    if missing.empty:
        print("✅ No missing values found.\n")

    else:
        missing_df = (
            pd.DataFrame({
                "Missing Count": missing,
                "Missing %": (missing / len(df) * 100).round(2)
            })
            .sort_values(by="Missing Count", ascending=False)
        )

        display(missing_df)

    print()

======================================================================
Influencers
======================================================================
✅ No missing values found.


======================================================================
Campaigns
======================================================================
✅ No missing values found.


======================================================================
Campaign Performance
======================================================================

                 Missing Count  Missing %
Main_Product_ID             36       60.0

======================================================================
Orders
======================================================================
✅ No missing values found.


======================================================================
Products
======================================================================
✅ No missing values found.


======================================================================
Customers
======================================================================
✅ No missing values found.

In [ ]:
campaign_perf[
    campaign_perf["Main_Product_ID"].isna()
][["Campaign_ID",
   "Product_Focus_Type",
   "Main_Product_ID"]].head(20)

   Campaign_ID Product_Focus_Type Main_Product_ID
1       CMP005           Category             NaN
3       CMP006           Category             NaN
4       CMP007         Collection             NaN
8       CMP006           Category             NaN
9       CMP001           Category             NaN
11      CMP001           Category             NaN
12      CMP003         Collection             NaN
13      CMP005           Category             NaN
14      CMP008           Category             NaN
15      CMP003         Collection             NaN
18      CMP006           Category             NaN
19      CMP001           Category             NaN
20      CMP003         Collection             NaN
22      CMP005           Category             NaN
23      CMP006           Category             NaN
24      CMP008           Category             NaN
26      CMP007         Collection             NaN
27      CMP005           Category             NaN
30      CMP005           Category             NaN
31      CMP007         Collection             NaN

In [ ]:
campaign_perf[
    (campaign_perf["Product_Focus_Type"] == "Single Product") &
    (campaign_perf["Main_Product_ID"].isna())
]

Empty DataFrame
Columns: [Source_Influencer_ID, Campaign_ID, Conversions, Revenue_Generated, Cost, ROI, Product_Focus_Type, Main_Product_ID]
Index: []

In [ ]:
# ============================================
# Duplicate Record Assessment
# ============================================

for name, df in datasets.items():

    print("=" * 70)
    print(name)
    print("=" * 70)

    duplicate_rows = df.duplicated().sum()

    print(f"Duplicate Rows : {duplicate_rows}")

    print()

======================================================================
Influencers
======================================================================
Duplicate Rows : 0

======================================================================
Campaigns
======================================================================
Duplicate Rows : 0

======================================================================
Campaign Performance
======================================================================
Duplicate Rows : 0

======================================================================
Orders
======================================================================
Duplicate Rows : 0

======================================================================
Products
======================================================================
Duplicate Rows : 0

======================================================================
Customers
======================================================================
Duplicate Rows : 0

In [ ]:
# ============================================
# Primary Key Uniqueness Check
# ============================================

primary_keys = {
    "Influencers": "Influencer_ID",
    "Campaigns": "Campaign_ID",
    "Products": "Product_ID",
    "Customers": "Customer_ID",
    "Orders": "Order_ID"
}

for dataset_name, key in primary_keys.items():

    df = datasets[dataset_name]

    duplicates = df[key].duplicated().sum()

    print("="*70)
    print(dataset_name)
    print("="*70)

    print(f"Primary Key : {key}")
    print(f"Duplicate Keys : {duplicates}")

    if duplicates == 0:
        print("✅ Primary key is unique.\n")
    else:
        print("❌ Duplicate primary keys found.\n")

======================================================================
Influencers
======================================================================
Primary Key : Influencer_ID
Duplicate Keys : 0
✅ Primary key is unique.

======================================================================
Campaigns
======================================================================
Primary Key : Campaign_ID
Duplicate Keys : 0
✅ Primary key is unique.

======================================================================
Products
======================================================================
Primary Key : Product_ID
Duplicate Keys : 0
✅ Primary key is unique.

======================================================================
Customers
======================================================================
Primary Key : Customer_ID
Duplicate Keys : 0
✅ Primary key is unique.

======================================================================
Orders
======================================================================
Primary Key : Order_ID
Duplicate Keys : 0
✅ Primary key is unique.

In [ ]:
# ============================================
# Composite Key Check
# ============================================

duplicate_composite = campaign_perf.duplicated(
    subset=["Source_Influencer_ID", "Campaign_ID"]
).sum()

print("Duplicate Composite Keys:", duplicate_composite)

if duplicate_composite == 0:
    print("✅ Composite key is unique.")
else:
    print("❌ Duplicate composite keys found.")

Duplicate Composite Keys: 0
✅ Composite key is unique.

In [ ]:
# ============================================
# Referential Integrity Check
# ============================================

checks = [
    ("Orders", orders["Customer_ID"], customers["Customer_ID"], "Customer_ID"),
    ("Orders", orders["Product_ID"], products["Product_ID"], "Product_ID"),
    ("Orders", orders["Campaign_ID"], campaigns["Campaign_ID"], "Campaign_ID"),
    ("Orders", orders["Source_Influencer_ID"], influencers["Influencer_ID"], "Source_Influencer_ID"),

    ("Campaign Performance", campaign_perf["Campaign_ID"], campaigns["Campaign_ID"], "Campaign_ID"),
    ("Campaign Performance", campaign_perf["Source_Influencer_ID"], influencers["Influencer_ID"], "Source_Influencer_ID"),
    (
        "Campaign Performance",
        campaign_perf["Main_Product_ID"].dropna(),
        products["Product_ID"],
        "Main_Product_ID"
    )
]

for table, child, parent, key in checks:

    invalid = (~child.isin(parent)).sum()

    print("=" * 70)
    print(table)
    print("=" * 70)

    print(f"Foreign Key : {key}")
    print(f"Invalid References : {invalid}")

    if invalid == 0:
        print("✅ Referential integrity maintained.\n")
    else:
        print("❌ Invalid foreign key references found.\n")

======================================================================
Orders
======================================================================
Foreign Key : Customer_ID
Invalid References : 0
✅ Referential integrity maintained.

======================================================================
Orders
======================================================================
Foreign Key : Product_ID
Invalid References : 0
✅ Referential integrity maintained.

======================================================================
Orders
======================================================================
Foreign Key : Campaign_ID
Invalid References : 0
✅ Referential integrity maintained.

======================================================================
Orders
======================================================================
Foreign Key : Source_Influencer_ID
Invalid References : 0
✅ Referential integrity maintained.

======================================================================
Campaign Performance
======================================================================
Foreign Key : Campaign_ID
Invalid References : 0
✅ Referential integrity maintained.

======================================================================
Campaign Performance
======================================================================
Foreign Key : Source_Influencer_ID
Invalid References : 0
✅ Referential integrity maintained.

======================================================================
Campaign Performance
======================================================================
Foreign Key : Main_Product_ID
Invalid References : 0
✅ Referential integrity maintained.

In [ ]:
# ============================================
# Categorical Consistency Check
# ============================================

categorical_columns = {
    "Influencers": ["Gender", "Platform", "Tier", "Location"],
    "Campaigns": ["Product_Category", "Goal_Type", "Target_Gender", "Product_Focus_Type", "Platform"],
    "Campaign Performance": ["Product_Focus_Type"],
    "Orders": ["Channel"],
    "Products": ["Category", "Sub_Category", "Gender_Target", "Season"],
    "Customers": ["Gender", "Location", "Income_Bracket", "Preferred_Style"]
}

for dataset_name, columns in categorical_columns.items():

    print("="*80)
    print(dataset_name)
    print("="*80)

    df = datasets[dataset_name]

    for col in columns:
        print(f"\n{col}:")
        print(sorted(df[col].dropna().unique()))

    print("\n")

================================================================================
Influencers
================================================================================

Gender:
['Female', 'Male', 'Unisex']

Platform:
['Instagram', 'TikTok', 'YouTube']

Tier:
['Macro', 'Mega', 'Micro', 'Nano']

Location:
['Andhra Pradesh', 'Bihar', 'Delhi', 'Gujarat', 'Haryana', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Punjab', 'Rajasthan', 'Tamil Nadu']


================================================================================
Campaigns
================================================================================

Product_Category:
['Accessories', 'Dresses', 'Jackets', 'Pants', 'Tops']

Goal_Type:
['Awareness', 'Conversions']

Target_Gender:
['Female', 'Male', 'Unisex']

Product_Focus_Type:
['Category', 'Collection', 'Single Product']

Platform:
['Instagram', 'TikTok', 'YouTube']


================================================================================
Campaign Performance
================================================================================

Product_Focus_Type:
['Category', 'Collection', 'Single Product']


================================================================================
Orders
================================================================================

Channel:
['Instagram', 'TikTok', 'YouTube']


================================================================================
Products
================================================================================

Category:
['Accessories', 'Dresses', 'Jackets', 'Pants', 'Tops']

Sub_Category:
['Cotton', 'Denim', 'Leather', 'Polyester', 'Silk']

Gender_Target:
['Female', 'Male', 'Unisex']

Season:
['All-Season', 'Summer', 'Winter']


================================================================================
Customers
================================================================================

Gender:
['Female', 'Male', 'Other']

Location:
['Andhra Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Odisha', 'Punjab', 'Rajasthan', 'Tamil Nadu', 'Telangana', 'Uttar Pradesh', 'West Bengal']

Income_Bracket:
['High', 'Low', 'Medium']

Preferred_Style:
['Athleisure', 'Boho', 'Casual', 'Formal', 'Luxury', 'Streetwear']

In [ ]:
# ============================================
# Outlier Detection using IQR
# ============================================

numerical_columns = {
    "Influencers": ["Follower_Count", "Avg_Cost_Per_Post", "Audience_Location_Match_pct"],
    "Campaigns": ["Budget", "Conversion_Rate_Target_pct"],
    "Campaign Performance": ["Conversions", "Revenue_Generated", "Cost", "ROI"],
    "Orders": ["Quantity", "Unit_Price", "Discount_Amount", "Total_Amount"],
    "Products": ["Price"],
    "Customers": ["Age", "Lifetime_Value", "Avg_Order_Value"]
}

for dataset_name, cols in numerical_columns.items():

    print("="*80)
    print(dataset_name)
    print("="*80)

    df = datasets[dataset_name]

    for col in cols:

        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)

        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        outliers = df[(df[col] < lower) | (df[col] > upper)]

        print(f"{col}: {len(outliers)} outliers")

    print()

================================================================================
Influencers
================================================================================
Follower_Count: 1 outliers
Avg_Cost_Per_Post: 3 outliers
Audience_Location_Match_pct: 0 outliers

================================================================================
Campaigns
================================================================================
Budget: 0 outliers
Conversion_Rate_Target_pct: 0 outliers

================================================================================
Campaign Performance
================================================================================
Conversions: 0 outliers
Revenue_Generated: 1 outliers
Cost: 0 outliers
ROI: 12 outliers

================================================================================
Orders
================================================================================
Quantity: 10961 outliers
Unit_Price: 0 outliers
Discount_Amount: 3583 outliers
Total_Amount: 2746 outliers

================================================================================
Products
================================================================================
Price: 0 outliers

================================================================================
Customers
================================================================================
Age: 453 outliers
Lifetime_Value: 3268 outliers
Avg_Order_Value: 2260 outliers

In [ ]:
orders["Quantity"].describe()

count    100000.000000
mean          1.141250
std           0.433798
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Quantity, dtype: float64

In [ ]:
%whos

Variable              Type         Data/Info
--------------------------------------------
IQR                   float64      3331.1275000000005
Q1                    float64      1636.2675
Q3                    float64      4967.395
campaign_perf         DataFrame       Source_Influencer_ID C<...>Product          PRD003
campaigns             DataFrame      Campaign_ID Product_Cat<...>YouTube  \n9     TikTok
categorical_columns   dict         n=6
checks                list         n=7
child                 Series       0     PRD021\n2     PRD01<...>Product_ID, dtype: object
col                   str          Avg_Order_Value
cols                  list         n=3
columns               list         n=4
customers             DataFrame          Customer_ID  Gender<...>[90000 rows x 11 columns]
dataset_name          str          Customers
datasets              dict         n=6
df                    DataFrame          Customer_ID  Gender<...>[90000 rows x 11 columns]
duplicate_composite   int64        0
duplicate_rows        int64        0
duplicates            int64        0
influencers           DataFrame       Influencer_ID         <...>                   61.0
invalid               int64        0
key                   str          Main_Product_ID
lower                 float64      -3360.423750000001
missing               Series       Series([], dtype: int64)
missing_df            DataFrame                     Missing <...>            36       60.0
name                  str          Customers
np                    module       <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
numerical_columns     dict         n=6
orders                DataFrame            Order_ID Order_Da<...>100000 rows x 12 columns]
outliers              DataFrame          Customer_ID  Gender<...>n[2260 rows x 11 columns]
parent                Series       0     PRD001\n1     PRD00<...>Product_ID, dtype: object
pd                    module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
primary_keys          dict         n=5
products              DataFrame       Product_ID     Categor<...>01-09  \n24  2024-08-04
table                 str          Campaign Performance
upper                 float64      9964.08625

In [ ]:
invalid_dates = campaigns[campaigns["Start_Date"] > campaigns["End_Date"]]

print("Invalid campaigns:", len(invalid_dates))
invalid_dates

Invalid campaigns: 0

Empty DataFrame
Columns: [Campaign_ID, Product_Category, Budget, Goal_Type, Target_Gender, Product_Focus_Type, Start_Date, End_Date, Conversion_Rate_Target_pct, Platform]
Index: []

In [ ]:
products[products["Price"] <= 0]

Empty DataFrame
Columns: [Product_ID, Category, Sub_Category, Price, Gender_Target, Season, Launch_Date]
Index: []

In [ ]:
campaigns[campaigns["Budget"] <= 0]

Empty DataFrame
Columns: [Campaign_ID, Product_Category, Budget, Goal_Type, Target_Gender, Product_Focus_Type, Start_Date, End_Date, Conversion_Rate_Target_pct, Platform]
Index: []

In [ ]:
campaign_perf[campaign_perf["Revenue_Generated"] < 0]

Empty DataFrame
Columns: [Source_Influencer_ID, Campaign_ID, Conversions, Revenue_Generated, Cost, ROI, Product_Focus_Type, Main_Product_ID]
Index: []

In [ ]:
campaign_perf["ROI"].describe()

count      60.000000
mean      296.010625
std       345.593406
min        57.239500
25%       114.076650
50%       164.939950
75%       219.125975
max      1439.259300
Name: ROI, dtype: float64

In [ ]:
orders[
    orders["Discount_Amount"] >
    (orders["Quantity"] * orders["Unit_Price"])
]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Quantity, Unit_Price, Discount_Code_Used, Discount_Amount, Source_Influencer_ID, Campaign_ID, Total_Amount, Channel]
Index: []

In [ ]:
expected_total = (
    orders["Quantity"] * orders["Unit_Price"]
    - orders["Discount_Amount"]
)

difference = abs(expected_total - orders["Total_Amount"])

difference.describe()

count    1.000000e+05
mean     2.048978e-14
std      1.282083e-13
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.637979e-12
dtype: float64

In [ ]:
campaign_perf.describe()

       Conversions  Revenue_Generated           Cost          ROI
count    60.000000       6.000000e+01      60.000000    60.000000
mean   1666.666667       5.880848e+06   48460.000000   296.010625
std    1139.446263       4.130432e+06   47949.999381   345.593406
min     290.000000       1.148903e+06     900.000000    57.239500
25%     965.500000       2.819270e+06   24000.000000   114.076650
50%    1135.000000       4.629839e+06   24000.000000   164.939950
75%    2699.750000       7.642153e+06  120000.000000   219.125975
max    4724.000000       1.525416e+07  120000.000000  1439.259300

In [ ]:
orders.describe()

,Order_Date,Quantity,Unit_Price,Discount_Amount,Total_Amount
count,100000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2024-11-15 03:29:09.600000256,1.141250,3375.173720,326.381517,3528.508953
min,2024-01-01 00:00:00,1.000000,608.000000,0.010000,516.810000
25%,2024-06-09 00:00:00,1.000000,1760.000000,129.490000,1602.530000
50%,2024-11-15 00:00:00,1.000000,3127.000000,246.880000,2974.535000
75%,2025-04-23 00:00:00,1.000000,5292.000000,438.732500,5018.802500
max,2025-09-30 00:00:00,4.000000,8526.000000,3889.500000,32145.850000
std,NaN,0.433798,2014.164069,287.751065,2631.587807

In [ ]:
customers.describe()

                Age  Lifetime_Value  Avg_Order_Value
count  90000.000000    90000.000000     90000.000000
mean      29.659189     3920.565504      3505.638801
std        6.706927     3068.140003      2493.589653
min       18.000000      516.810000       516.810000
25%       25.000000     1662.555000      1636.267500
50%       30.000000     3173.745000      3004.920000
75%       34.000000     5334.312500      4967.395000
max       60.000000    43256.220000     24962.280000